apiVersion: "stable.agones.dev/v1alpha1"
kind: GameServer
metadata:
  name: "factorio"
spec:
  portPolicy: "dynamic"
  containerPort: 34197
  container: "factorio"
  protocol: "UDP"
  template:
    spec:
      containers:
      - name: factorio
        image: outlaw11a/agones-factorio